name: 'Security Action (legacy)'
description: 'Collect and Generalize multiple CI Security checks'
inputs:
# in-name:
#   description: yadda yadda
#   required: true
#   default: 0
  github_token:
    description: |
      Secret token to push review comments, and
      interact with the repository systematically
    required: true
  slack_token:
    description: |
      Secret token to forward findings to slack
    required: false
  assignees:
    description: assign PR to the people linked
    default: |
      thypon
      bcaller
  hotwords:
    description: body hotwords which should trigger the action
    default: |
      password
      cryptography
      login
      policy
      safebrowsing
      safe browsing
      csp
      url parse
      urlparse
      :disableDigestUpdates
      pinDigest
  debug:
    description: enables debug output for this action
    required: false
  enabled:
    description: may disable the whole action, big red button for emergency cases
    default: 'true'
  baseline_scan_only:
    description: compare changed files with the base ref, do not scan the entire repo with reviewdog
    default: 'true'
  pip_audit_pypi_index_url:
    description: Pypi index for pip-audit to use in case you have a private index
    required: false
  pip_audit_pypi_insecure_hosts:
    description: Hosts for --trusted-host in pip-audit in case you have an untrusted private index, comma separated
    required: false
  gh_to_slack_user_map:
    description: JSON map of github usernames to slack usernames
    required: false
  codeql_config:
    description: |
      Path to the CodeQL config file
    required: false
  codeql_enabled:
    description: enables codeql action
    required: false
runs:
  using: 'composite'
  steps:
    - uses: ${{ github.action_path }}/actions/reviewdog
      with:
        github_token: ${{ inputs.github_token }}
        slack_token: ${{ inputs.slack_token }}
        assignees: ${{ inputs.assignees }}
        hotwords: ${{ inputs.hotwords }}
        debug: ${{ inputs.debug }}
        enabled: ${{ inputs.enabled }}
        baseline_scan_only: ${{ inputs.baseline_scan_only }}
        pip_audit_pypi_index_url: ${{ inputs.pip_audit_pypi_index_url }}
        pip_audit_pypi_insecure_hosts: ${{ inputs.pip_audit_pypi_insecure_hosts }}
        gh_to_slack_user_map: ${{ inputs.gh_to_slack_user_map }}
    - uses: ${{ github.action_path }}/actions/codeql
      with:
        debug: ${{ inputs.debug }}
        codeql_config_file: ${{ inputs.codeql_config }}
        codeql_enabled: ${{ inputs.codeql_enabled }}