name: 'Security Action'
description: 'Collect and Generalize multiple CI Security checks'
inputs:
# in-name:
#   description: yadda yadda
#   required: true
#   default: 0
  github_token:
    description: |
      Secret token to push review comments, and
      interact with the repository systematically
    required: true
  slack_token:
    description: |
      Secret token to forward findings to slack
    required: false
  assignees:
    description: assign PR to the people linked
    default: |
      thypon
      bcaller
  debug:
    description: enables debug output for this action
    required: false
  codeql_config:
    description: CodeQL configuration config config
    default: ./.github/codeql/codeql-config.yml
  enabled:
    type: boolean
    description: may disable the whole action, big red button for emergency cases
    default: true
# outputs:
#   out-name:
#     description: yadda yadda
#     value: ${{ steps.output-step-id.outputs.output-name }}
runs:
  using: 'composite'
  steps:
    - name: Get changed files
      if: ${{ inputs.enabled && github.event_name == 'pull_request' }}
      id: changed-files
      uses: tj-actions/changed-files@v36
      with:
        separator: '\\0'
    - name: Store reviewdog enabled
      if: ${{ inputs.enabled && steps.changed-files.outputs.all_changed_files != '' && github.event_name == 'pull_request' && github.event.pull_request.draft == false && github.actor != 'dependabot[bot]' && (!matrix.language || matrix.language == 'generic') }}
      id: reviewdog-enabled
      shell: bash
      run: |
        set -x
        echo "value=true" >> $GITHUB_OUTPUT
    - name: Store codeql enabled
      if: ${{ inputs.enabled && github.event.pull_request.draft == false && github.actor != 'dependabot[bot]' && matrix.language && matrix.language != 'generic' }}
      id: codeql-enabled
      shell: bash
      run: |
        set -x
        # enable codeql only if it's a public repo
        if curl --retry 5 -s -I ${{github.event.repository.url}} | head -n1 | grep 200 >/dev/null  ; then
          echo "value=true" >> $GITHUB_OUTPUT
        fi
# REVIEWDOG Steps
# REVIEWDOG Setup
    - name: Write changed files to file
      if: ${{ steps.reviewdog-enabled.outputs.value }}
      id: write-changed-files
      shell: bash
      run: |
        set -e
        printf -- '${{ steps.changed-files.outputs.all_changed_files }}' >> ${{ github.action_path }}/assets/all_changed_files.txt
        printf '${{ steps.changed-files.outputs.any_changed }}'
    - id: comments-before
      if: ${{ steps.reviewdog-enabled.outputs.value }}
      uses: actions/github-script@v6
      with:
          script: |
            var query = `query($owner:String!, $name:String!, $prnumber:Int!) { 
              repository(owner:$owner, name:$name) { 
                pullRequest(number:$prnumber) {
                  reviewThreads(last:100) {
                    nodes {
                      isOutdated
                      comments(first:1) {
                        totalCount
                        nodes {
                          id
                          author {
                            login
                          }
                          bodyText
                        }
                      }
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              prnumber: context.issue.number
            }
            const result = await github.graphql(query, variables);
            const threads = result.repository.pullRequest.reviewThreads;
            const deletableComments = threads.nodes.filter(
              reviewThread => (
                reviewThread.isOutdated === true &&
                reviewThread.comments.totalCount === 1 &&
                reviewThread.comments.nodes[0].author.login === "github-actions" &&
                reviewThread.comments.nodes[0].bodyText.includes("Cc @brave/sec-team")
              )
            ).map(
              reviewThread => (
                reviewThread.comments.nodes[0].id
              )
            );
            console.log("Delete", deletableComments);
            if (deletableComments) {
              deleteMutation = `mutation($comment:ID!) {
                deletePullRequestReviewComment(input: {id:$comment}) {
                  clientMutationId
                }
              }`;
              for (const commentId of deletableComments) {
                console.log("Deleting %s", commentId);
                await github.graphql(deleteMutation, {comment: commentId});
              }
            }
            var commentsNumber = threads.nodes.filter(
              reviewThread => (
                !(reviewThread.isOutdated === true && reviewThread.comments.totalCount === 1) &&
                reviewThread.comments.nodes[0].author.login === "github-actions" &&
                reviewThread.comments.nodes[0].bodyText.includes("Cc @brave/sec-team")
              )
            ).length;
            console.log("Comments: %d", commentsNumber);
            return commentsNumber;

    - if: ${{ steps.reviewdog-enabled.outputs.value }}
      name: Cache pip cache
      id: cache-pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip/
        key: ${{ runner.os }}-pip
    - if: ${{ steps.reviewdog-enabled.outputs.value }}
      id: assignees
      env:
        ASSIGNEES: ${{inputs.assignees}}
      run: echo "value=$(echo "$ASSIGNEES" | sed 's|\([^ ]\)|@\1|' | tr -s '\n' ' ')" >> $GITHUB_OUTPUT
      shell: bash
    - if: ${{ steps.reviewdog-enabled.outputs.value }}
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
    - if: ${{ steps.reviewdog-enabled.outputs.value }}
      name: Setup Ruby
      id: ruby
      uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939
      env:
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      with:
        ruby-version: '3.2'
        bundler-cache: true
    - if: ${{ steps.reviewdog-enabled.outputs.value }}
      name: Install semgrep & pip-audit
      shell: bash
      run: |
        python3 -m pip install --disable-pip-version-check -r ${{ github.action_path }}/requirements.txt
    - if: ${{ steps.reviewdog-enabled.outputs.value }}
      name: Install xmllint for safesvg
      uses: awalsh128/cache-apt-pkgs-action@1850ee53f6e706525805321a3f2f863dcf73c962
      with:
          packages: libxml2-utils
          version: 1.0
    - if: ${{ steps.reviewdog-enabled.outputs.value }}
      name: Install tfsec
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with: # Grab a specific tag with caching
        repo: aquasecurity/tfsec
        tag: v1.28.1
        cache: enable
    - if: ${{ steps.reviewdog-enabled.outputs.value && inputs.debug}}
      env:
        ASSIGNEES: ${{steps.assignees.outputs.value}}
      run: ${{ github.action_path }}/assets/debug.sh
      shell: bash
# REVIEWDOG Run
    - if: ${{ steps.reviewdog-enabled.outputs.value }}
      name: Run reviewdog
      shell: bash
      env:
        ASSIGNEES: ${{steps.assignees.outputs.value}}
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
      run: ${{ github.action_path }}/assets/reviewdog.sh
    - id: comments-after
      if: ${{ steps.reviewdog-enabled.outputs.value }}
      uses: actions/github-script@v6
      with:
          script: |
            var query = `query($owner:String!, $name:String!, $prnumber:Int!) { 
              repository(owner:$owner, name:$name) { 
                pullRequest(number:$prnumber) {
                  reviewThreads(last:100) {
                    nodes {
                      isOutdated
                      comments(first:1) {
                        totalCount
                        nodes {
                          author {
                            login
                          }
                          bodyText
                        }
                      }
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              prnumber: context.issue.number
            }
            const result = await github.graphql(query, variables);
            const threads = result.repository.pullRequest.reviewThreads;
            var commentsNumber = threads.nodes.filter(
              reviewThread => (
                !(reviewThread.isOutdated === true && reviewThread.comments.totalCount === 1) &&
                reviewThread.comments.nodes[0].author.login === "github-actions" &&
                reviewThread.comments.nodes[0].bodyText.includes("Cc @brave/sec-team")
              )
            ).length;
            console.log("Comments: %d", commentsNumber);
            return commentsNumber;
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ steps.reviewdog-enabled.outputs.value && (steps.comments-before.outputs.result != steps.comments-after.outputs.result) }}
      with:
        github_token: ${{ inputs.github_token }}
        labels: needs-security-review
    - uses: actions-ecosystem/action-add-assignees@v1
      if: ${{ steps.reviewdog-enabled.outputs.value && (steps.comments-before.outputs.result != steps.comments-after.outputs.result) }}
      with:
        github_token: ${{ inputs.github_token }}
        assignees: ${{ inputs.assignees }}
    - if: ${{ steps.reviewdog-enabled.outputs.value && hashFiles('reviewdog.fail.log') }}
      shell: bash
      run: |
        set +x
        echo -e '\033[0;31mThis action encountered an error while reporting the following findings via the Github API:'
        cat reviewdog.fail.log | sed 's/^/\x1B[0;34m/'
        echo -e '\033[0;31mThe failure of this action should not prevent you from merging your PR. Please report this failure to the maintainers of https://github.com/brave/security-action \033[0m'
    - if: ${{ steps.reviewdog-enabled.outputs.value && !inputs.slack_token && hashFiles('reviewdog.fail.log') }}
      shell: bash
      run: exit 1
    - uses: actions-ecosystem/action-slack-notifier@v1
      if: ${{ steps.reviewdog-enabled.outputs.value && inputs.slack_token && hashFiles('reviewdog.fail.log') }}
      with:
        slack_token: ${{ inputs.slack_token }}
        message: |
          [semgrep] @${{ github.actor }} action failed, plz take a look. /cc ${{steps.assignees.outputs.value}}
        channel: secops-hotspots
        color: red
        verbose: true
    - uses: actions-ecosystem/action-slack-notifier@v1
      if: ${{ steps.reviewdog-enabled.outputs.value && inputs.slack_token && (steps.comments-before.outputs.result != steps.comments-after.outputs.result) }}
      with:
        slack_token: ${{ inputs.slack_token }}
        message: |
          [semgrep] @${{ github.actor }} pushed commits. /cc ${{steps.assignees.outputs.value}}
        channel: secops-hotspots
        color: green
        verbose: true
# CodeQL Steps
    - if: ${{ steps.codeql-enabled.outputs.value && hashFiles(inputs.codeql_config) }}
      name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        config-file: ${{ inputs.codeql_config }}
    - if: ${{ steps.codeql-enabled.outputs.value && !hashFiles(inputs.codeql_config)}}
      name: Initialize CodeQL (without config)
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    - if: ${{ steps.codeql-enabled.outputs.value }}
      name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - if: ${{ steps.codeql-enabled.outputs.value }}
      name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
#    - run: echo ${{ inputs.in-name }}
#      shell: bash
#    - id: output-step-id
#      run: echo "output-name=antani" >> $GITHUB_OUTPUT
#      shell bash

