name: security
on:
  workflow_dispatch:
  push:
    branches: [main, master, staging, development, devel, dev, prod]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main, master, staging, development, devel, dev]
  merge_group:
permissions:
  contents: read
  pull-requests: write
jobs:
  security:
    name: security
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: brave/security-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          slack_token: ${{ secrets.HOTSPOTS_SLACK_TOKEN }}
