name: Copy repo secrets to org secrets

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  copy-secrets:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.ORG_SECRETS_MANAGER_TOKEN }}
          GH_TO_SLACK_USER_MAP: ${{ secrets.GH_TO_SLACK_USER_MAP }}
        run: |
          gh secret set GH_TO_SLACK_USER_MAP -o "${GITHUB_REPOSITORY_OWNER:?}" <<<"${GH_TO_SLACK_USER_MAP:?}"

          # FIXME: -r/--repos repositories List of repositories that can access an organization or user secret
          #    or  -v/--visibility string  Set visibility for an organization secret: {all|private|selected} (default "private")
