name: Weekly Dependabot Nudge

on:
  schedule:
    # Run at 9am UTC every Monday
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
              with:
                node-version: '20.x'
            - id: npm
              run: cd ${{ github.workspace }}; npm ci
              shell: bash
            - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
              env:
                SLACK_TOKEN: ${{ secrets.HOTSPOTS_SLACK_TOKEN }}
                SLACK_CHANNEL: '#secops-hotspots'
                DEBUG: false
              with:
                github-token: ${{ secrets.DEPENDABOT_NUDGE_GITHUB_TOKEN }}
                script: |
                  const debug = process.env.DEBUG === 'true';
                  const { default: sendSlackMessage } = await import('${{ github.workspace }}/src/sendSlackMessage.js');
                  const { default: dependabotNudge } = await import('${{ github.workspace }}/src/dependabotNudge.js');
                  const messages = await dependabotNudge({debug, org: process.env.GITHUB_REPOSITORY_OWNER, github: github, minlevel: 'medium'});

                  for (const message of messages) {
                    try {
                      await sendSlackMessage({debug, username: 'dependabot', message: message, channel: process.env.SLACK_CHANNEL, token: process.env.SLACK_TOKEN});
                    } catch (error) {
                      if (debug)
                        console.log(error);
                    }
                  }


