name: Weekly Dependabot Auto Dismiss

on:
  schedule:
    # Run at 24:00 UTC every Monday
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
              with:
                node-version: '20.x'
            - id: npm
              run: cd ${{ github.workspace }}; npm ci
              shell: bash
            - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
              env:
                SLACK_TOKEN: ${{ secrets.HOTSPOTS_SLACK_TOKEN }}
                SLACK_CHANNEL: '#secops-hotspots'
                DEBUG: false
              with:
                github-token: ${{ secrets.DEPENDABOT_AUTO_DISMISS_GITHUB_TOKEN }}
                script: |
                  const debug = process.env.DEBUG === 'true';
                  const { default: sendSlackMessage } = await import('${{ github.workspace }}/src/sendSlackMessage.js');
                  const { default: dependabotDismiss } = await import('${{ github.workspace }}/src/dependabotDismiss.js');
                  const message = await dependabotDismiss({debug, org: process.env.GITHUB_REPOSITORY_OWNER, github: github, dependabotDismissConfig: '${{ github.workspace }}/.github/dependabot-dismiss.txt'});
                  if (message.length > 0)
                    await sendSlackMessage({debug, username: 'dependabot-auto-dismiss', message: message, channel: process.env.SLACK_CHANNEL, token: process.env.SLACK_TOKEN});


