name: loop-reviewdog-test
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  loop:
    name: loop-reviewdog-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # CodeQL analyzed languages
      matrix:
        language: [ 'generic', 'javascript', '' ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - run: |
          pwd
          tree -a
        shell: bash
      - uses: ./actions/reviewdog
        with:
          debug: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gh_to_slack_user_map: ${{ secrets.GH_TO_SLACK_USER_MAP }}
