name: loop
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  loop:
    name: loop
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # CodeQL analyzed languages
      matrix:
        language: [ 'generic', 'javascript', '' ]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
      - run: |
          pwd
          tree -a
        shell: bash
      - uses: ./
        with:
          debug: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
