# action that runs monthly and check if all repositories in the organization are following the renovate central configuration
# to all repositories in this organization
name: Renovate Sanity Check
on:
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20.x'
      - id: npm
        run: cd ${{ github.workspace }}; npm ci
        shell: bash
      - name: run
        id: run
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          DEBUG: false
        with:
          github-token: ${{ secrets.CUSTOM_PROPERTY_MANAGER_GITHUB_TOKEN }}
          script: |
            console.log('${{ github.workspace }}/src/renovateSanityCheck.js');
            const { default: renovateSanityCheck } = await import('${{ github.workspace }}/src/renovateSanityCheck.js');
            return await renovateSanityCheck({
                org: process.env.GITHUB_REPOSITORY_OWNER,
                github: github,
                debug: process.env.DEBUG
            });
      - uses: actions-ecosystem/action-slack-notifier@fc778468d09c43a6f4d1b8cccaca59766656996a # v1.1.0
        if: ${{ fromJson(steps.run.outputs.result) != '' }}
        with:
          slack_token: ${{ secrets.HOTSPOTS_SLACK_TOKEN }}
          message: |
            [renovate-sanity-check] ${{ fromJson(steps.run.outputs.result) }}
          channel: secops-hotspots
          color: yellow
          verbose: false
